-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 09:04:36 2024
-- model: New model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Ciudad` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Usuariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC) VISIBLE,
  UNIQUE INDEX `Usuariocol_UNIQUE` (`Usuariocol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Obra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Obra` (
  `ID_OBRA` INT NOT NULL AUTO_INCREMENT,
  `Título` VARCHAR(45) NOT NULL,
  `Formato` VARCHAR(45) NULL,
  `Género` VARCHAR(45) NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`ID_OBRA`),
  INDEX `fk_Obra_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Obra_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_intercambia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario_intercambia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_intercambia` (
  `Usuario_idUsuario` INT NOT NULL,
  `Obra_ID_OBRA` INT NOT NULL,
  `Fecha` DATE NULL DEFAULT GETDATE();,
  `Duración` TIME NOT NULL,
  `Confirmación` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`Usuario_idUsuario`, `Obra_ID_OBRA`),
  INDEX `fk_Usuario_has_Obra_Obra1_idx` (`Obra_ID_OBRA` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Obra_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Obra_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Obra_Obra1`
    FOREIGN KEY (`Obra_ID_OBRA`)
    REFERENCES `mydb`.`Obra` (`ID_OBRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
